version: '3.8'

services:
  php:
    build:
      context: ./php
    volumes:
      - ./..:/var/www/html
    working_dir: /var/www/html
    networks:
      - mynetwork
    environment:
      - APP_ENV=dev
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./..:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - mynetwork
    restart: unless-stopped

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - mynetwork
    restart: unless-stopped

networks:
  mynetwork:
